### ISSUE TITLE
HPE Alletra Storage MP not supported

### ISSUE THREAD

**Issue by iulianroman** [hpe-storage/array-exporter#16]
I tried to configured the exporter to use the WSAPI enabled on Alletra MP, but it does not work. Is this model supported ? if yes, is there any configuration which needs to be performed ?

**Comment by datamattsson** [comment]
It has not been tested and there's no efforts being made to support the platform AFAIK.

**Comment by datamattsson** [comment]
v1.0.3 supports Alletra Storage MP. https://hpe-storage.github.io/array-exporter/releases/index.html#hpe_storage_array_exporter_for_prometheus_103
